#!/bin/bash

for m in 60 55 50 45 40 35 30 25 20 15;
#for m in 60 15;
do
  echo ${m}
  python mkWS.py --iD /eos/user/t/twamorka/2May2020_CommonBDTPairing/CatTrain_phoMVA_nophoMVACut_nomixweight/ --i signal_m_${m}_transformedMVA --m ${m} --WP 'veryLoose' --opt signal --nCat 0,1,2,3,4 --mvaCut "bdtTransformed>=0.3, bdtTransformed<0.3 && bdtTransformed>=0.19, bdtTransformed<0.19 && bdtTransformed>= 0.14, bdtTransformed<0.14 && bdtTransformed>=0.06, bdtTransformed<0.06" --addc '1>0' --suf 'CombinedTraining_phoMVA_vLooseMVACut'${m} --oD /eos/user/t/twamorka/2May2020_CommonBDTPairing/CatTrain_phoMVA_vLoosephoMVACut_nomixweight/
  python shiftHiggsDatasets.py --i output_signal_m_${m}_transformedMVA_WS_CombinedTraining_phoMVA_vLooseMVACut${m} --inDir /eos/user/t/twamorka/2May2020_CommonBDTPairing/CatTrain_phoMVA_vLoosephoMVACut_nomixweight/ --m ${m} --nCat 0,1,2,3,4 --s CombinedTraining_phoMVA_vLooseMVACut${m} --outDir /eos/user/t/twamorka/2May2020_CommonBDTPairing/CatTrain_phoMVA_vLoosephoMVACut_nomixweight/
  python mkWS.py --iD /eos/user/t/twamorka/2May2020_CommonBDTPairing/CatTrain_phoMVA_nophoMVACut_nomixweight/ --i data_all_transformedMVA --m ${m} --WP 'veryLoose' --opt data --nCat 0,1,2,3,4 --mvaCut "bdtTransformed>=0.3, bdtTransformed<0.3 && bdtTransformed>=0.19, bdtTransformed<0.19 && bdtTransformed>= 0.14, bdtTransformed<0.14 && bdtTransformed>=0.06, bdtTransformed<0.06" --addc '1>0' --suf 'CombinedTraining_phoMVA_vLooseMVACut' --oD /eos/user/t/twamorka/2May2020_CommonBDTPairing/CatTrain_phoMVA_vLoosephoMVACut_nomixweight/
  #python mkWS.py --iD /eos/user/t/twamorka/5May2020_m${m}_BDTPairing/CatTrain_allVars/ --i signal_m_${m}_transformedMVA --m ${m} --WP veryLoose --opt signal --nCat 0,1 --mvaCut "bdtTransformed>=0.026, bdtTransformed<0.026" --addc '1>0' --suf 'm15_training_allVars' --oD /eos/user/t/twamorka/5May2020_m${m}_BDTPairing/CatTrain_allVars/13May2020/
  #python shiftHiggsDatasets.py --i output_signal_m_${m}_transformedMVA_WS_m${m}_training_allVars --inDir /eos/user/t/twamorka/5May2020_m${m}_BDTPairing/CatTrain_allVars/13May2020/ --m ${m} --nCat 0,1 --s m${m}_training_allVars --outDir /eos/user/t/twamorka/5May2020_m${m}_BDTPairing/CatTrain_allVars/13May2020/
  #python mkWS.py --iD /eos/user/t/twamorka/5May2020_m${m}_BDTPairing/CatTrain_allVars/ --i data_all_transformedMVA --m ${m} --WP veryLoose --opt data --nCat 0,1 --mvaCut "bdtTransformed>=0.026, bdtTransformed<0.026" --addc '1>0' --suf 'm15_training_allVars' --oD /eos/user/t/twamorka/5May2020_m${m}_BDTPairing/CatTrain_allVars/13May2020/
  #python mkWS.py --iD /eos/user/t/twamorka/2May2020_CommonBDTPairing/CatTrain_allVars/ --i signal_m_${m}_transformedMVA --m ${m} --WP veryLoose --opt signal --nCat 0,1,2,3,4 --mvaCut "bdtTransformed>=0.27, bdtTransformed<0.27 && bdtTransformed>=0.15, bdtTransformed<0.15 && bdtTransformed>=0.11, bdtTransformed<0.11 && bdtTransformed>=0.04, bdtTransformed<0.04" --addc '1>0' --suf 'common_training_allVars' --oD /eos/user/t/twamorka/2May2020_CommonBDTPairing/CatTrain_allVars/13May2020/
  #python shiftHiggsDatasets.py --i output_signal_m_${m}_transformedMVA_WS_common_training_allVars --inDir /eos/user/t/twamorka/2May2020_CommonBDTPairing/CatTrain_allVars/13May2020/ --m ${m} --nCat 0,1,2,3,4 --s common_training_allVars --outDir /eos/user/t/twamorka/2May2020_CommonBDTPairing/CatTrain_allVars/13May2020/
  #python mkWS.py --iD /eos/user/t/twamorka/2May2020_CommonBDTPairing/VBF_Gamma34_Loose/CatTrain_allVars_combined_plusOthers/ --i signal_m_${m}_transformedMVA --m ${m} --WP Loose --opt signal --nCat 0,1,2,3,4 --mvaCut "bdtTransformed>=0.5,bdtTransformed<0.5 && bdtTransformed>=0.35, bdtTransformed<0.35 && bdtTransformed>=0.2, bdtTransformed<0.2 && bdtTransformed>=0.1, bdtTransformed<0.1" --addc '1>0' --suf '7May_Combined_VBF_otherVars' --oD /eos/user/t/twamorka/2May2020_CommonBDTPairing/VBF_Gamma34_Loose/CatTrain_allVars_combined_plusOthers/
  #python mkWS.py --iD /eos/user/t/twamorka/2May2020_CommonBDTPairing/CatTrain_allVars/ --i signal_m_${m}_transformedMVA --m ${m} --WP veryLoose --opt signal --nCat 0,1,2,3 --mvaCut "bdtTransformed>=0.21, bdtTransformed<0.21 && bdtTransformed>=0.11, bdtTransformed<0.11 && bdtTransformed>=0.04, bdtTransformed<0.04" --addc '1>0' --suf '4May_NCut4' --oD /eos/user/t/twamorka/2May2020_CommonBDTPairing/CatTrain_allVars/
done
